# Generated by Django 3.0.9 on 2020-08-21 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anzeige',
            name='author',
        ),
        migrations.AddField(
            model_name='anzeige',
            name='frei_ab',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='anzeige',
            name='warmmiete',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anzeige',
            name='zimmergröße',
            field=models.IntegerField(default=0),
        ),
    ]
