# Generated by Django 3.0.9 on 2020-08-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wg', '0002_auto_20200821_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anzeige',
            old_name='zimmergröße',
            new_name='zimmergroesse',
        ),
    ]
