# Generated by Django 3.0.9 on 2020-08-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wg', '0003_auto_20200828_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='anzeige',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
