# Generated by Django 3.0.9 on 2020-09-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wg', '0005_anzeige_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='anzeige',
            name='adresse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anzeige',
            name='kontakt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anzeige',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
