# Generated by Django 3.0.9 on 2020-09-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wg', '0006_auto_20200908_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anzeige',
            name='adresse',
            field=models.CharField(blank=True, max_length=37, null=True),
        ),
        migrations.AlterField(
            model_name='anzeige',
            name='kontakt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anzeige',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
